# Generated by Django 2.1 on 2019-01-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SGCNo', models.CharField(max_length=20)),
                ('ZSDName', models.CharField(max_length=20)),
                ('Time', models.DateTimeField()),
                ('Spot', models.CharField(max_length=50)),
                ('Cause', models.TextField()),
                ('Money', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Accident',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('CNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('CType', models.CharField(max_length=10)),
                ('COilConsumpution', models.IntegerField()),
                ('isAvailable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Car',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.CharField(max_length=10)),
                ('DSex', models.BooleanField(default=True)),
                ('DAge', models.SmallIntegerField()),
                ('PhoneNum', models.CharField(max_length=11)),
                ('Hiredata', models.DateField()),
                ('isAvailable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='Proposer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CType', models.CharField(max_length=10)),
                ('Num', models.IntegerField()),
                ('Mileage', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('isRecived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Proposer',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.CharField(max_length=20)),
                ('STime', models.DateTimeField()),
                ('ETime', models.DateTimeField()),
                ('OilConsumpution', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('CNo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cno_in_record',
                                          to='TransportationManagement.Car')),
                ('DNo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dno_in_record',
                                          to='TransportationManagement.Driver')),
            ],
            options={
                'db_table': 'Record',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='accident',
            name='ZSCNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cno_case_accident',
                                    to='TransportationManagement.Car'),
        ),
        migrations.AddField(
            model_name='accident',
            name='ZSDNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dno_case_accident',
                                    to='TransportationManagement.Driver'),
        ),
    ]
