# Generated by Django 2.1 on 2019-01-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TransportationManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='ZSCNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cno_case_accident',
                                    to='TransportationManagement.Car'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='ZSDNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dno_case_accident',
                                    to='TransportationManagement.Driver'),
        ),
        migrations.AlterField(
            model_name='record',
            name='CNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cno_in_record',
                                    to='TransportationManagement.Car'),
        ),
        migrations.AlterField(
            model_name='record',
            name='DNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dno_in_record',
                                    to='TransportationManagement.Driver'),
        ),
    ]
