# Generated by Django 2.1 on 2019-01-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TransportationManagement', '0003_auto_20190103_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposer',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
